### ISSUE TITLE
Running to docker

### ISSUE THREAD

**Issue by laronlineworld** [xops/expedition#18]
How to run expedition on docker? any ways?

**Comment by DRIgnazGortngschirl** [comment]
1.st I would build the Dockerfile 

2.nd Try this docker-compose.yml


```
version: '3.3'
networks:
  web:
    external: true
  back-tier: null
services:
 expedition:
    ports:
      - '8999:80'
    image: 'expedition:latest'
    networks:
      - back-tier
    restart: unless-stopped
```
3.rd access via the exposed poorts
